/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IchnaeaCore } from "./IchnaeaCore";
export * as factories from "./factories";
export { IchnaeaCore__factory } from "./factories/IchnaeaCore__factory";
